apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-dep1
  labels:
    app: iperf3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      hostname: iperf3-dep1
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - master
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        command: ['/bin/sh', '-c', 'sleep infinity']
        # To benchmark manually: kubectl exec iperf3-clients-jlfxq -- /bin/sh -c 'iperf3 -c iperf3-server'
        ports:
        - containerPort: 5201
          protocol: TCP
          name: iperf3-dep1-tcp
        - containerPort: 5201
          protocol: UDP
          name: iperf3-dep1-udp
      terminationGracePeriodSeconds: 0
      nodeSelector:
        id: node1

---

apiVersion: v1
kind: Service
metadata:
  name: iperf3-dep1
spec:
  selector:
    app: iperf3
  ports:
  - name: iperf-tcp
    protocol: TCP
    port: 5201
    targetPort: iperf3-dep1-tcp
  - name: iperf-udp
    protocol: UDP
    port: 5201
    targetPort: iperf3-dep1-udp
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-dep2
  labels:
    app: iperf3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      hostname: iperf3-dep2
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - master
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        command: ['/bin/sh', '-c', 'sleep infinity']
        # To benchmark manually: kubectl exec iperf3-clients-jlfxq -- /bin/sh -c 'iperf3 -c iperf3-server'
        ports:
        - containerPort: 5201
          protocol: TCP
          name: iperf3-dep2-tcp
        - containerPort: 5201
          protocol: UDP
          name: iperf3-dep2-udp
      terminationGracePeriodSeconds: 0
      nodeSelector:
        id: node1

---

apiVersion: v1
kind: Service
metadata:
  name: iperf3-dep2
spec:
  selector:
    app: iperf3
  ports:
  - name: iperf-tcp
    protocol: TCP
    port: 5201
    targetPort: iperf3-dep2-tcp
  - name: iperf-udp
    protocol: UDP
    port: 5201
    targetPort: iperf3-dep2-udp
    
---